# Generated by Django 4.2.1 on 2023-05-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First', models.CharField(max_length=35)),
                ('last', models.CharField(max_length=35)),
                ('contact', models.IntegerField()),
                ('Password', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
