# Generated by Django 4.2.1 on 2023-05-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0002_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(choices=[('USA', 'United States'), ('CAN', 'Canada'), ('UK', 'United Kingdom'), ('IND', 'INDIA')], default='', max_length=50),
        ),
    ]
