# Generated by Django 4.2.1 on 2023-05-23 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=10)),
                ('cat_desc', models.CharField(max_length=20)),
                ('img', models.ImageField(upload_to='category_image/')),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=110, null=True)),
                ('pro_name', models.CharField(max_length=20)),
                ('Pro_Description', models.CharField(default='Default description', max_length=20)),
                ('size', models.IntegerField(null=True)),
                ('price', models.IntegerField()),
                ('pro_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product_app.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='ProductImage')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product_app.products')),
            ],
        ),
    ]
