# Generated by Django 4.2.1 on 2023-05-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_products_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='cat_desc',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='categories',
            name='cat_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='Pro_Description',
            field=models.CharField(default='Default description', max_length=2000),
        ),
        migrations.AlterField(
            model_name='products',
            name='pro_name',
            field=models.CharField(max_length=200),
        ),
    ]
