# Generated by Django 4.2.1 on 2023-05-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_alter_categories_cat_desc_alter_categories_cat_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='pro_id',
            field=models.IntegerField(null=True),
        ),
    ]
