# Generated by Django 4.2.1 on 2023-05-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0004_products_pro_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='pro_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
