# Generated by Django 4.1.5 on 2023-05-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0006_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First', models.CharField(max_length=35)),
                ('last', models.CharField(max_length=35)),
                ('contact', models.IntegerField()),
                ('Password', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('country', models.CharField(choices=[('USA', 'United States'), ('CAN', 'Canada'), ('UK', 'United Kingdom'), ('IND', 'INDIA')], default='', max_length=50)),
            ],
        ),
    ]
