# Generated by Django 4.1.5 on 2023-05-30 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0007_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='Imag_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pro_name', to='product_app.categories'),
        ),
    ]
